In [1]:
import numpy as np

Array Operations and Broadcasting

In [10]:
#Given a 3D array a with shape (2, 3, 4) and a 2D array b with shape (3, 4), perform element-wise multiplication between a and b using broadcasting
a = np.random.rand(2, 3, 4)
b = np.random.rand(3, 4)

result = a * b

print("Array a:")
print(a)
print("\nArray b:")
print(b)
print("\nResult of element-wise multiplication:")
print(result)


Array a:
[[[0.67727261 0.01824466 0.13585268 0.78159169]
  [0.49840248 0.46386531 0.25630503 0.35426916]
  [0.11296768 0.65424204 0.48598414 0.95650154]]

 [[0.21456855 0.57174673 0.06612506 0.16846335]
  [0.29002785 0.26696179 0.85853089 0.30373012]
  [0.89997564 0.90590538 0.72986804 0.05866793]]]

Array b:
[[0.02870555 0.12798423 0.68843115 0.65857164]
 [0.3523478  0.24961757 0.99801306 0.27399808]
 [0.06243159 0.14890315 0.53557877 0.03160672]]

Result of element-wise multiplication:
[[[0.01944148 0.00233503 0.09352522 0.51473412]
  [0.17561102 0.11578893 0.25579577 0.09706907]
  [0.00705275 0.0974187  0.26028279 0.03023188]]

 [[0.00615931 0.07317457 0.04552255 0.11094519]
  [0.10219067 0.06663835 0.85682504 0.08322147]
  [0.05618691 0.13489216 0.39090182 0.0018543 ]]]


In [19]:
#Implement a function that takes two 2D arrays c and d with different shapes and performs element-wise operations (addition, subtraction, multiplication, and division) between them using broadcasting. Handle the case where broadcasting is not possible

def elementwise_operations(c, d):
    try:
        # Perform element-wise addition using broadcasting
        addition = c + d
        
        # Perform element-wise subtraction using broadcasting
        subtraction = c - d
        
        # Perform element-wise multiplication using broadcasting
        multiplication = c * d
        
        # Perform element-wise division using broadcasting
        division = c / d
        
        return addition, subtraction, multiplication, division, None
    except ValueError as e:
        return None, None, None, None, str(e)

# Example usage:
c = np.random.rand(2, 3)
d = np.random.rand(3, 1)

addition, subtraction, multiplication, division, error = elementwise_operations(c, d)

print("Array c:")
print(c)
print("\nArray d:")
print(d)

if error is None:
    print("\nAddition result:")
    print(addition)
    print("\nSubtraction result:")
    print(subtraction)
    print("\nMultiplication result:")
    print(multiplication)
    print("\nDivision result:")
    print(division)
else:
    print("\nError:", error)






Array c:
[[0.19160847 0.40002268 0.65683675]
 [0.57422251 0.53985553 0.75615126]]

Array d:
[[0.93928526]
 [0.95455955]
 [0.46311139]]

Error: operands could not be broadcast together with shapes (2,3) (3,1) 


In [23]:
#Create a 2D array e with shape (5, 3) and a 1D array f with length 5. Compute the outer product of e and f using broadcasting.
e = np.random.rand(5, 3)


f = np.random.rand(5)
f_reshaped = f[:, np.newaxis]  

outer_product = e * f_reshaped

print("Array e:")
print(e)
print("\nArray f:")
print(f)
print("\nReshaped Array f:")
print(f_reshaped)
print("\nOuter Product:")
print(outer_product)


Array e:
[[0.19656889 0.45254956 0.17293764]
 [0.16840195 0.1045495  0.35885306]
 [0.3464704  0.3365644  0.07024485]
 [0.9660567  0.7253117  0.3602451 ]
 [0.89912931 0.84094149 0.17162536]]

Array f:
[0.43896552 0.33095109 0.71245541 0.68396345 0.90749622]

Reshaped Array f:
[[0.43896552]
 [0.33095109]
 [0.71245541]
 [0.68396345]
 [0.90749622]]

Outer Product:
[[0.08628696 0.19865365 0.07591366]
 [0.05573281 0.03460077 0.11876281]
 [0.24684471 0.23978713 0.05004633]
 [0.66074748 0.49608669 0.24639448]
 [0.81595645 0.76315122 0.15574937]]


Indexing and Slicing

In [25]:
#Given a 3D array g with shape (4, 3, 2), extract every other element along the first and second dimensions, but keep all elements along the third dimension

g = np.random.rand(4, 3, 2)

extracted_g = g[::2, ::2, :]

print("Original array g:")
print(g)
print("\nExtracted array g (every other element along first and second dimensions):")
print(extracted_g)


Original array g:
[[[0.14601574 0.55545229]
  [0.60039299 0.79189487]
  [0.06298864 0.28268461]]

 [[0.77491108 0.72367613]
  [0.36949518 0.90436148]
  [0.17591243 0.22472219]]

 [[0.41111636 0.43121626]
  [0.84667231 0.97176733]
  [0.56251489 0.66947352]]

 [[0.41011966 0.14560015]
  [0.65074645 0.85962186]
  [0.34253942 0.08649406]]]

Extracted array g (every other element along first and second dimensions):
[[[0.14601574 0.55545229]
  [0.06298864 0.28268461]]

 [[0.41111636 0.43121626]
  [0.56251489 0.66947352]]]


In [27]:
#Create a function that takes a 2D array h and an array of row indices i and column indices j. The function should return a new array k where k[m, n] is the sum of the elements in h along the diagonal specified by i[m] and j[n].
def diagonal_sums(h, i, j):
    k = np.zeros((len(i), len(j)))
    for m in range(len(i)):
        for n in range(len(j)):
            k[m, n] = np.sum(np.diagonal(h, offset=(j[n] - i[m])))
    return k

h = np.random.rand(5, 5)
i = np.array([0, 1, 2])
j = np.array([1, 2, 3])

k = diagonal_sums(h, i, j)

print("Array h:")
print(h)
print("\nRow indices i:")
print(i)
print("\nColumn indices j:")
print(j)
print("\nResulting array k (sums of diagonals):")
print(k)


Array h:
[[0.78517088 0.86477069 0.34215401 0.15338571 0.04026779]
 [0.35774024 0.81562797 0.3154014  0.53669831 0.73529543]
 [0.57586466 0.82092955 0.79823997 0.55257075 0.56521015]
 [0.50885484 0.16774046 0.80279106 0.06136221 0.2687065 ]
 [0.02332828 0.25321215 0.83382136 0.06241115 0.59474004]]

Row indices i:
[0 1 2]

Column indices j:
[1 2 3]

Resulting array k (sums of diagonals):
[[2.00144934 1.44406248 0.88868114]
 [3.05514107 2.00144934 1.44406248]
 [2.043872   3.05514107 2.00144934]]


In [29]:
#Implement a function that takes a 2D array l and returns a new array m where each element in m is the product of the corresponding row and column means in l.
def row_col_mean_product(l):
    row_means = np.mean(l, axis=1, keepdims=True)
    col_means = np.mean(l, axis=0, keepdims=True)
    m = row_means * col_means
    return m
l = np.random.rand(4, 5)

m = row_col_mean_product(l)

print("Array l:")
print(l)
print("\nRow means:")
print(np.mean(l, axis=1))
print("\nColumn means:")
print(np.mean(l, axis=0))
print("\nResulting array m (product of row and column means):")
print(m)


Array l:
[[0.24133099 0.65501308 0.09243437 0.49667617 0.9411487 ]
 [0.62309995 0.80603684 0.55596756 0.97502599 0.62352834]
 [0.83081214 0.81024016 0.68982673 0.90983797 0.89408865]
 [0.48775342 0.6965042  0.87458691 0.82241154 0.55582608]]

Row means:
[0.48532066 0.71673173 0.82696113 0.68741643]

Column means:
[0.54574912 0.74194857 0.55320389 0.80098792 0.75364794]

Resulting array m (product of row and column means):
[[0.26486333 0.36008297 0.26848128 0.38873599 0.36576092]
 [0.39115572 0.53177809 0.39649878 0.57409346 0.5401634 ]
 [0.45131331 0.61356263 0.45747811 0.66238587 0.62323755]
 [0.37515691 0.51002763 0.38028144 0.55061225 0.51806997]]


Array Manipulation

In [31]:
#Given a 2D array n with shape (4, 6), reshape it into a 3D array with shape (2, 2, 6) and then flatten it back to a 2D array with shape (4, 6).
import numpy as np

n = np.random.rand(4, 6)

n_reshaped = n.reshape(2, 2, 6)

n_flattened = n_reshaped.reshape(4, 6)

print("Original 2D array n:")
print(n)
print("\nReshaped to 3D array (2, 2, 6):")
print(n_reshaped)
print("\nFlattened back to 2D array (4, 6):")
print(n_flattened)


Original 2D array n:
[[0.45938389 0.14427883 0.12349357 0.63537308 0.0244478  0.55816079]
 [0.64421133 0.29060806 0.4014869  0.34192625 0.78779635 0.06871253]
 [0.3016512  0.71796709 0.08681608 0.54636608 0.95036154 0.49099812]
 [0.91415012 0.72980478 0.71133844 0.04919384 0.59208304 0.21808593]]

Reshaped to 3D array (2, 2, 6):
[[[0.45938389 0.14427883 0.12349357 0.63537308 0.0244478  0.55816079]
  [0.64421133 0.29060806 0.4014869  0.34192625 0.78779635 0.06871253]]

 [[0.3016512  0.71796709 0.08681608 0.54636608 0.95036154 0.49099812]
  [0.91415012 0.72980478 0.71133844 0.04919384 0.59208304 0.21808593]]]

Flattened back to 2D array (4, 6):
[[0.45938389 0.14427883 0.12349357 0.63537308 0.0244478  0.55816079]
 [0.64421133 0.29060806 0.4014869  0.34192625 0.78779635 0.06871253]
 [0.3016512  0.71796709 0.08681608 0.54636608 0.95036154 0.49099812]
 [0.91415012 0.72980478 0.71133844 0.04919384 0.59208304 0.21808593]]


In [33]:
#Implement a function that takes a 2D array o and rolls it along the first axis by a specified number of positions. For example, if the input array is [[1, 2, 3], [4, 5, 6]] and the number of positions is 1, the output should be [[4, 5, 6], [1, 2, 3]].
def roll_array(o, positions):
    return np.roll(o, positions, axis=0)
o = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
positions = 1

rolled_o = roll_array(o, positions)

print("Original array o:")
print(o)
print("\nRolled array o by 1 position:")
print(rolled_o)


Original array o:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Rolled array o by 1 position:
[[10 11 12]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [35]:
#Create a function that takes a 2D array p and replaces all occurrences of a specified value x with the mean of the neighboring elements (horizontally and vertically) in the array
def replace_with_mean(p, x):
  
    rows, cols = p.shape

    result = np.copy(p)
    
  
    for i in range(rows):
        for j in range(cols):
            if p[i, j] == x:
                neighbors = []
                if i > 0:
                    neighbors.append(p[i-1, j])
                if i < rows - 1:
                    neighbors.append(p[i+1, j])
                if j > 0:
                    neighbors.append(p[i, j-1])
                if j < cols - 1:
                    neighbors.append(p[i, j+1])
                if neighbors:
                    result[i, j] = np.mean(neighbors)
    
    return result

p = np.array([[1, 2, 3], [4, 9, 6], [7, 9, 9], [10, 11, 12]])
x = 9

replaced_p = replace_with_mean(p, x)

print("Original array p:")
print(p)
print("\nArray p with occurrences of 9 replaced by the mean of neighboring elements:")
print(replaced_p)



Original array p:
[[ 1  2  3]
 [ 4  9  6]
 [ 7  9  9]
 [10 11 12]]

Array p with occurrences of 9 replaced by the mean of neighboring elements:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  9  9]
 [10 11 12]]
